name: Docker image buildx and push

on: [push]

jobs:
  GCC11:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push gcc11
        uses: docker/build-push-action@v3
        with:
          file: gcc11.dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: samaitc/gcc11:latest

      - name: Build and push ubuntu2204
        uses: docker/build-push-action@v3
        with:
          file: ubuntu2204.dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: samaitc/gcc11:latest

      - name: Build and push demo001
        uses: docker/build-push-action@v3
        with:
          file: demo001.dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: samaitc/gcc11:latest
